Movies/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include
from django.contrib.auth import views as auth_views
from mywebsite.views import (home_view)
from account.views import (register_view,login_view,logout_view,add_favorite,remove_favorite)
from movie.views import predict

urlpatterns = [
    #admin
    path('admin/', admin.site.urls),
    #home
    path('', home_view, name='home'),
    #signup
    path('register/', register_view, name="register"),
    #login
    path('login/', login_view, name="login"),
    #logout
    path('logout/', logout_view, name="logout"),
    # Reset Password URL
    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name='account/password_management/password_reset.html'),
         name='password_reset'),
    # Reset Password Request Sent
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='account/password_management/password_reset_done.html'), name='password_reset_done'),
    # Reset Password Form
    path('password_reset/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='account/password_management/password_reset_form.html'), name='password_reset_confirm'),
    # Reset Password Done
    path('password_reset/reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='account/password_management/password_reset_complete.html'), name='password_reset_complete'),
    # path('password_reset/done/',
    #      auth_views.PasswordResetCompleteView.as_view(template_name='account/password_management/password_reset_done.html'),
    #      name='password_reset_done'),
    #
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    #
    # path('reset/done/',
    #      auth_views.PasswordResetCompleteView.as_view(template_name='account/password_management/password_reset_complete.html'),
    #      name='password_reset_complete'),
    #Profile
    path('profile/',include('account.urls',namespace='profile')),
    #Movie
    path('Movie/',include('movie.urls',namespace='movie')),
    #Add/remove movie to/from favorite
    path('add_favorite/<movieid>/',add_favorite,name='add_favorite'),
    path('remove_favorite/<movieid>/',remove_favorite,name='add_favorite'),

    path('mysuggestions/',predict,name='mysuggestions'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path


from account.views import profile_view,profile_settings_view,Custom_Password_Change,profile_delete
from django.contrib.auth import views as auth_views
app_name = 'profile'

urlpatterns = [
    #Profile
    path('',profile_view,name='view'),
    #Settings
    path('edit',profile_settings_view,name='edit'),
    #Password Change
    path('password/',
         Custom_Password_Change.as_view(template_name='account/password_management/password_change.html'),
         name='password_change'),
    #Password Change Done
    path('password/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='account/password_management/password_change_done.html'), name='password_change_done'),
    #Delete Account
    path('delete',profile_delete,name='delete'),
]

movie/urls.py
from django.urls import path

from movie.views import movie_view


app_name = 'movie'

urlpatterns = [
    #Profile
    path('<movie_id>/',movie_view,name='view'),

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/lightslider.min.css' %}">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/lightslider.min.js' %}"></script>

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>What Now ?</title>
</head>

<body>
<a class="close-navbar-toggler collapsed" data-bs-toggle="collapse" data-bs-target="#navbar"></a>
<nav class="navbar navbar-expand-lg bg-light navbar-light flex-lg-nowrap flex-wrap p-3 px-lg-5">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">
            <span>What</span><span> Now ?</span>
        </a>
        <button class="navbar-toggler ms-auto" type="button" data-bs-toggle="collapse" data-bs-target="#navbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="navbar">

            <ul class="navbar-nav text-center fs-5 fw-bold  ms-5 gap-1">
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link text-nowrap" href="{% url 'profile:view' %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor"
                                 class="bi bi-person-circle me-1" viewBox="0 0 16 16">
                                <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"></path>
                                <path fill-rule="evenodd"
                                      d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"></path>
                            </svg>
                            My Profile
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-nowrap" href="{% url 'mysuggestions' %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor"
                                 class="bi bi-film me-1" viewBox="0 0 16 16">
                                <path d="M0 1a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v14a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V1zm4 0v6h8V1H4zm8 8H4v6h8V9zM1 1v2h2V1H1zm2 3H1v2h2V4zM1 7v2h2V7H1zm2 3H1v2h2v-2zm-2 3v2h2v-2H1zM15 1h-2v2h2V1zm-2 3v2h2V4h-2zm2 3h-2v2h2V7zm-2 3v2h2v-2h-2zm2 3h-2v2h2v-2z"></path>
                            </svg>
                            My Suggestions
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-nowrap" href="{% url 'profile:edit' %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor"
                                 class="bi bi-gear-fill me-1" viewBox="0 0 16 16">
                                <path d="M9.405 1.05c-.413-1.4-2.397-1.4-2.81 0l-.1.34a1.464 1.464 0 0 1-2.105.872l-.31-.17c-1.283-.698-2.686.705-1.987 1.987l.169.311c.446.82.023 1.841-.872 2.105l-.34.1c-1.4.413-1.4 2.397 0 2.81l.34.1a1.464 1.464 0 0 1 .872 2.105l-.17.31c-.698 1.283.705 2.686 1.987 1.987l.311-.169a1.464 1.464 0 0 1 2.105.872l.1.34c.413 1.4 2.397 1.4 2.81 0l.1-.34a1.464 1.464 0 0 1 2.105-.872l.31.17c1.283.698 2.686-.705 1.987-1.987l-.169-.311a1.464 1.464 0 0 1 .872-2.105l.34-.1c1.4-.413 1.4-2.397 0-2.81l-.34-.1a1.464 1.464 0 0 1-.872-2.105l.17-.31c.698-1.283-.705-2.686-1.987-1.987l-.311.169a1.464 1.464 0 0 1-2.105-.872l-.1-.34zM8 10.93a2.929 2.929 0 1 1 0-5.86 2.929 2.929 0 0 1 0 5.858z"></path>
                            </svg>
                            Settings
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-nowrap" href="{% url 'logout' %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor"
                                 class="bi bi-box-arrow-right me-1" viewBox="0 0 16 16">
                                <path fill-rule="evenodd"
                                      d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z"></path>
                                <path fill-rule="evenodd"
                                      d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"></path>
                            </svg>
                            Log out
                        </a>
                    </li>

                {% else %}

                    <li class="nav-item">
                        <a class="nav-link text-nowrap" href="{% url 'login' %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor"
                                 class="bi bi-box-arrow-in-left me-1" viewBox="0 0 16 16">
                                <path fill-rule="evenodd"
                                      d="M10 3.5a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-2a.5.5 0 0 1 1 0v2A1.5 1.5 0 0 1 9.5 14h-8A1.5 1.5 0 0 1 0 12.5v-9A1.5 1.5 0 0 1 1.5 2h8A1.5 1.5 0 0 1 11 3.5v2a.5.5 0 0 1-1 0v-2z"></path>
                                <path fill-rule="evenodd"
                                      d="M4.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H14.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3z"></path>
                            </svg>
                            Login
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-nowrap" href="{% url 'register' %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor"
                                 class="bi bi-person-plus-fill me-1" viewBox="0 0 16 16">
                                <path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"></path>
                                <path fill-rule="evenodd"
                                      d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"></path>
                            </svg>
                            Sign Up
                        </a>
                    </li>

                {% endif %}

            </ul>
            <!-- Change This -->
            <form class="d-none mt-3 mt-lg-0 d-lg-flex ms-auto w-25">
                <div class="input-group rounded">
                    <input type="search" class="form-control rounded" placeholder="Search" aria-label="Search"
                           aria-describedby="search-addon"/>
                    <span class="input-group-text border-0" id="search-addon">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                             class="bi bi-search" viewBox="0 0 16 16">
                          <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"></path>
                        </svg>
                    </span>
                </div>
            </form>
            <form class="d-flex justify-content-center mt-3 mt-lg-0 d-lg-none">
                <div class="input-group rounded">
                    <input type="search" class="form-control rounded" placeholder="Search" aria-label="Search"
                           aria-describedby="search-addon"/>
                    <span class="input-group-text border-0" id="search-addon">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                             class="bi bi-search" viewBox="0 0 16 16">
                          <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"></path>
                        </svg>
                    </span>
                </div>
            </form>
        </div>
    </div>
</nav>

<div id="loading">
    <h1>Loading
        <div class="dots"><span class="dot z"></span><span class="dot f"></span><span class="dot s"></span><span
                class="dot t"><span class="dot l"></span></span></div>
    </h1>
</div>

{% block content %}
    {#Your Block Here#}
{% endblock content %}

<script src="{% static 'js/chart.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
</body>

</html>